/// Relative work-related AI adoption by education level, 2026 EU survey. Source: European Commission DG ECFIN Spring 2026 Economic Forecast.
table AIAdoptionByEducation
	lineageTag: 90d06d83-1f35-489e-9116-f9459310e5f3

	column EducationLevel
		dataType: string
		lineageTag: 1f3fb9e2-2309-42ea-88d5-6ffa06d4225e
		summarizeBy: none
		sourceColumn: EducationLevel

		annotation SummarizationSetBy = Automatic

	column RelativeWorkAIAdoption
		dataType: string
		lineageTag: 510eb918-b3bc-474f-984e-63b475542dd9
		summarizeBy: none
		sourceColumn: RelativeWorkAIAdoption

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 5e3b1ca5-c5e0-4dd5-a865-f1e811e1fd94
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		isHidden
		lineageTag: 9ce2c1b7-ec08-4301-8989-8b494ccd4d6d
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	partition AIAdoptionByEducation = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\AIAdoptionByEducation.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"EducationLevel", type text}, {"RelativeWorkAIAdoption", type text}, {"Year", Int64.Type}, {"Source", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

