/// EU enterprise AI adoption rate by economic sector (NACE), 2025. Source: Eurostat isoc_eb_ain2.
table AIAdoptionBySector
	lineageTag: 91bc79c7-7b60-4567-981a-8848b30b2d85

	/// Enterprise AI adoption rate for the selected economic sector, 2025.
	measure 'Sector Enterprise Adoption %' = SUM ( AIAdoptionBySector[EnterpriseAdoptionPct] )
		formatString: 0.0"%"
		lineageTag: 4a536604-e723-46a1-a932-bd19e63ca0ad

	column Sector
		dataType: string
		lineageTag: 0e8e5339-e3d7-4638-bfde-e6ce731914fb
		summarizeBy: none
		sourceColumn: Sector

		annotation SummarizationSetBy = Automatic

	column EnterpriseAdoptionPct
		dataType: decimal
		isHidden
		formatString: 0.0"%"
		lineageTag: 944a9105-26b5-4d13-9c35-a6f359ea43b9
		summarizeBy: none
		sourceColumn: EnterpriseAdoptionPct

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 702761c6-0edb-4dd6-a695-d4c8677cb918
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		isHidden
		lineageTag: ef85d436-9e0b-4a5b-a0d7-20ecc92bd7e4
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	partition AIAdoptionBySector = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Sandra\Power BI\Data\AIAdoptionBySector.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Sector", type text}, {"EnterpriseAdoptionPct", Currency.Type}, {"Year", Int64.Type}, {"Source", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

