/// Share of AI-using EU enterprises applying AI to each business function, by company size, 2025. Source: Eurostat isoc_eb_ai.
table AIAdoptionByBusinessFunction
	lineageTag: cce04a8d-a278-4d63-a8f9-44715528c19c

	/// Share of AI-using enterprises applying AI to the selected business function, 2025.
	measure 'Adoption Share %' = SUM ( AIAdoptionByBusinessFunction[PctOfAIUsingEnterprises] )
		formatString: 0.0"%"
		lineageTag: 529172f2-00d9-47ec-846d-6773e0322d9b

	column BusinessFunction
		dataType: string
		lineageTag: 3bbfdce5-0178-4447-a96c-2b6791105947
		summarizeBy: none
		sourceColumn: BusinessFunction

		annotation SummarizationSetBy = Automatic

	column EnterpriseSize
		dataType: string
		lineageTag: b7d1a55f-ab96-4bd6-9ef9-e4aa715d7dd9
		summarizeBy: none
		sourceColumn: EnterpriseSize

		annotation SummarizationSetBy = Automatic

	column PctOfAIUsingEnterprises
		dataType: decimal
		isHidden
		formatString: 0.0"%"
		lineageTag: 3ac47e8b-8596-4645-9736-3b1dfead772e
		summarizeBy: none
		sourceColumn: PctOfAIUsingEnterprises

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 46651af4-a2bb-4d30-b22c-3149ea6531fe
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		isHidden
		lineageTag: f7c7094c-7e67-467a-92e3-925e3a99897b
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	partition AIAdoptionByBusinessFunction = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Sandra\Power BI\Data\AIAdoptionByBusinessFunction.csv"),[Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"BusinessFunction", type text}, {"EnterpriseSize", type text}, {"PctOfAIUsingEnterprises", Currency.Type}, {"Year", Int64.Type}, {"Source", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

