/// EU enterprise AI adoption rate by company size band, 2025. Source: Eurostat isoc_eb_ai.
table AIAdoptionByEnterpriseSize
	lineageTag: 45a76517-85af-4b79-a69a-008eff5c0b52

	/// Enterprise AI adoption rate for the selected enterprise size band, 2025.
	measure 'Size Enterprise Adoption %' = SUM ( AIAdoptionByEnterpriseSize[EnterpriseAdoptionPct] )
		formatString: 0.0"%"
		lineageTag: d7b14d2a-12ac-43c5-a61f-9f9001c2847b

	column EnterpriseSize
		dataType: string
		lineageTag: 568ff3bb-a090-4b3a-81cc-ebd9decc93dc
		summarizeBy: none
		sourceColumn: EnterpriseSize

		annotation SummarizationSetBy = Automatic

	column EnterpriseAdoptionPct
		dataType: decimal
		isHidden
		formatString: 0.0"%"
		lineageTag: 0f638238-70bf-4163-88ce-12c5876a5d01
		summarizeBy: none
		sourceColumn: EnterpriseAdoptionPct

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: dff571bc-523b-4e74-8985-5fa397b71711
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		isHidden
		lineageTag: c0073437-31c0-429e-926b-904625034231
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	partition AIAdoptionByEnterpriseSize = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\AIAdoptionByEnterpriseSize.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"EnterpriseSize", type text}, {"EnterpriseAdoptionPct", Currency.Type}, {"Year", Int64.Type}, {"Source", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

